function varargout = model_help(varargin)
% MODEL_HELP MATLAB code for model_help.fig
%      MODEL_HELP, by itself, creates a new MODEL_HELP or raises the existing
%      singleton*.
%
%      H = MODEL_HELP returns the handle to a new MODEL_HELP or the handle to
%      the existing singleton*.
%
%      MODEL_HELP('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in MODEL_HELP.M with the given input arguments.
%
%      MODEL_HELP('Property','Value',...) creates a new MODEL_HELP or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before model_help_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to model_help_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES

% Edit the above text to modify the response to model_help model_help

% Last Modified by GUIDE v2.5 11-Jan-2011 22:55:48

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @model_help_OpeningFcn, ...
                   'gui_OutputFcn',  @model_help_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT


% --- Executes just before model_help is made visible.
function model_help_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to model_help (see VARARGIN)

% Choose default command line output for model_help
handles.output = hObject;

get_start_txt    = ['Multi-layers Canopy Soil Model (MLCan) brief description: Will be added                '         char(10), ...
                    '       '                                                           char(10), ...
                    '       '                                                           char(10), ...            
                    '   To start working with MLCan, do the following:          '       char(10), ...
                    '       '                                                           char(10), ...            
                    '       1. Create new project:                              '       char(10), ...            
                    '       '                                                           char(10), ...            
                    '               + On the menu bar, Select File/New.         '       char(10), ...            
                    '                 (Or click on New icon in the toolbar)     '       char(10), ...
                    '       '                                                           char(10), ...            
                    '               + Choose a file name for your project       '       char(10), ...     
                    '       '                                                           char(10), ...            
                    '               + Cick OK                                   '       char(10), ...     
                    '       '                                                           char(10), ...                                
                    '   Or'                                                             char(10), ...            
                    '       '                                                           char(10), ...                       
                    '       2. Open existing project:                            '      char(10), ...                        
                    '       '                                                           char(10), ...            
                    '               + On the menu bar, Select File/Open.         '      char(10), ...            
                    '                 (Or click on Open icon in the toolbar)     '      char(10), ...
                    '       '                                                           char(10), ...            
                    '               + Select existing project in the folder browser'    char(10), ...     
                    '       '                                                           char(10), ...
                    '               + Cick OK                                   '       char(10), ...     
                    '       '                                                           char(10), ...                                
                    ];
                
model_setup_txt = [ 'VEGETATION: Name of vegetations simulated                                              '       char(10), ...
                    '       '                                                                                       char(10), ...            
                    '       '                                                                                       char(10), ...                                
                    'GEOGRAPHIC : Latitude and Longitude measured in decimal degree                         '       char(10), ...            
                    '                          (used for calculating azimuth angles)                        '       char(10), ...            
                    '       '                                                                                       char(10), ...                                
                    '       '                                                                                       char(10), ...            
                    'ELEVATION: Altitude [m] of measured points (above Mean Sea Level - MSL)                '       char(10), ...                                
                    '       '                                                                                       char(10), ...            
                    '       '                                                                                       char(10), ...                                
                    'MINIMUM LAI: Leaf Area Index value chosen for start simulation                         '       char(10), ...                                
                    '       '                                                                                       char(10), ...            
                    '       '                                                                                       char(10), ...                                
                    'CANOPY STRUCTURE INFORMATION:                                                          '       char(10), ...            
                    '       # of canopy layers: The number that canopy is discretized for simulation        '       char(10), ...
                    '       '                                                                                       char(10), ...            
                    '       # of LAD layers: User-defined number of layers for describing LAD               '       char(10), ...    
                    '       (Users can either type or import from files)                                    '       char(10), ...                                
                    '       '                                                                                       char(10), ...            
                    '       '                                                                                       char(10), ...                                
                    'ROOT STRUCTURE INFORMATION:                                                            '       char(10), ...            
                    '       # of root layers: User-defined number of layers for root structure              '       char(10), ...    
                    '       (Users can either type or import from files)                                    '       char(10), ...                     '       '                                                                                       char(10), ...                                                  
                    ];                

option_txt =       ['PHOTOSYNTHESIS: Type of photosynthesis for simulated vegetation                        '       char(10), ...
                    '       '                                                                                       char(10), ...            
                    '       '                                                                                       char(10), ...                                
                    'ROOT HYDRAULIC CONDUCTIVITY (RHC): Increase of RHC along with soil depth               '       char(10), ...            
                    '       '                                                                                       char(10), ...                                
                    '       '                                                                                       char(10), ...            
                    'ROOT NUMERICAL MODEL: Numerical finite difference scheme for root model                '       char(10), ...                                
                    '       '                                                                                       char(10), ...            
                    '       '                                                                                       char(10), ...                                
                    'CARBON DIOXIDE CONCENTRATION: Value of surrounding CO2 concentration                   '       char(10), ...            
                    '       Ambient: Current condition, default value is set 370 [ppm]                      '       char(10), ...
                    '       Elevated: Value of CO2 concentration is increased due to global warming         '       char(10), ...                    
                    '       '                                                                                       char(10), ...            
                    '       '                                                                                       char(10), ...                                
                    'SOIL HEAT MODEL: Check to include soil heat transfer                                   '       char(10), ...            
                    '       '                                                                                       char(10), ...            
                    '       '                                                                                       char(10), ...                                
                    'TURBULENCE: Check to include turbulence transport of scalar microenvironment       	'       char(10), ...              
                    '       '                                                                                       char(10), ...            
                    '       '                                                                                       char(10), ...                                
                    'HYDRAULIC REDISTRIBUTION: Check to include Hydraulic distribution                      '       char(10), ...                                  
                    '       '                                                                                       char(10), ...            
                    '       '                                                                                       char(10), ...                                
                    ]; 

forcing_txt =      ['   To create new forcings file:                                                        '       char(10), ...
                    '       '                                                                                       char(10), ...            
                    '       + Select Create new forcing data option                                         '       char(10), ...            
                    '       '                                                                                       char(10), ...                                                    
                    '           - Choose a new file name by click on browse icon                            '       char(10), ...  
                    '       '                                                                                       char(10), ...                                                    
                    '           - Select appropriate time for input data in Create new forcing Panel        '       char(10), ... 
                    '                   + Starting time                                                     '       char(10), ... 
                    '                   + End time                                                          '       char(10), ... 
                    '                   + Time step                                                         '       char(10), ...                     
                    '       '                                                                                       char(10), ...                                                    
                    '           - User can either type or quickly import from files                         '       char(10), ...
                    '       '                                                                                       char(10), ...                                                    
                    '             (See user manual for file structure and format)                           '       char(10), ...
                    '       '                                                                                       char(10), ...                                
                    '       '                                                                                       char(10), ...         
                    '   To load existing data file:                                                         '       char(10), ...
                    '       '                                                                                       char(10), ...            
                    '       + Select Load data file option                                                  '       char(10), ...            
                    '       '                                                                                       char(10), ...                                                    
                    '           - Click on browse icon on the right                                         '       char(10), ...  
                    '       '                                                                                       char(10), ...                                                    
                    '           - Select forcing data file                                                  '       char(10), ... 
                    '              (If you open correctly, time information will be shown                   '       char(10), ... 
                    '               If not, repeat this step and choose correct file)                       '       char(10), ... 
                    '       '                                                                                       char(10), ...                          
                    ];  

initial_txt =      ['   Initial conditions for soil moisture and soil heat are required                     '       char(10), ...
                    '       '                                                                                       char(10), ...                                                    
                    '   To input initial conditions, do the following:                                      '       char(10), ...            
                    '       '                                                                                       char(10), ...                                                    
                    '       + Select Initial condition tab                                                  '       char(10), ...  
                    '       '                                                                                       char(10), ...                                                    
                    '           - First column in the root system table is root depth [m]                   '       char(10), ... 
                    '             (This column is extracted from root structure and is ineditable           '       char(10), ...                     
                    '       '                                                                                       char(10), ...                                                    
                    '           - Second column is initial soil moisture value at these root depths [%]     '       char(10), ... 
                    '       '                                                                                       char(10), ...                                                    
                    '           - Third column is initial soil heat value at these root depths [C]          '       char(10), ...
                    '       '                                                                                       char(10), ...                                                    
                    '             (Unless Heat model is include, soil heat initial column is disable)       '       char(10), ...
                    '       '                                                                                       char(10), ...
                    '       + Click OK                                                                      '       char(10), ...                      
                    ]; 
                
result_txt =       ['   Result viewer is used to produce plots for result file                              '       char(10), ...
                    '       '                                                                                       char(10), ...                                                    
                    '       '                                                                                       char(10), ...                                                    
                    '   To plot the result, do the following:                                               '       char(10), ...            
                    '       '                                                                                       char(10), ...                                                    
                    '       + Click on browse icon in Load result file panel                                '       char(10), ...  
                    '       '                                                                                       char(10), ...                                                    
                    '           - Select result file                                                        '       char(10), ... 
                    '       '                                                                                       char(10), ...                                                    
                    '           - Select variables that you want to plot                                    '       char(10), ... 
                    '       '                                                                                       char(10), ...                                                    
                    '           - Click on plot button                                                      '       char(10), ...
                    '       '                                                                                       char(10), ...                                                    
                    '           - Check "grid on" to show the grid                                          '       char(10), ...                    
                    '       '                                                                                       char(10), ...                                                    
                    '       + Select other variables                                                        '       char(10), ...                      
                    '       '                                                                                       char(10), ...                                                    
                    '           - Repeat above steps                                                        '       char(10), ...     
                    '       '                                                                                       char(10), ...
                    '       '                                                                                       char(10), ...                                                    
                    '   To plot the result, do the following:                                               '       char(10), ...            
                    '       '                                                                                       char(10), ...                    
                    '       + Open result file in matlab                                                    '       char(10), ...                      
                    ];                 
        
set(handles.txt_main,'String',get_start_txt);        

save './Temps/temp_variable.mat'...
        'get_start_txt' 'model_setup_txt' 'option_txt' 'forcing_txt'       ...
        'initial_txt'   'result_txt'     -append;

% Update handles structure
guidata(hObject, handles);

% UIWAIT makes model_help wait for user response (see UIRESUME)
% uiwait(handles.figure1);


% --- Outputs from this function are returned to the command line.
function varargout = model_help_OutputFcn(hObject, eventdata, handles) 
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Get default command line output from handles structure
varargout{1} = handles.output;


% --- If Enable == 'on', executes on mouse press in 5 pixel border.
% --- Otherwise, executes on mouse press in 5 pixel border or over txt_model_setup.
function txt_model_setup_ButtonDownFcn(hObject, eventdata, handles)
% hObject    handle to txt_model_setup (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)


% --- Executes on button press in but_get_start.
function but_get_start_Callback(hObject, eventdata, handles)
% hObject    handle to but_get_start (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
load './Temps/temp_variable.mat' 'get_start_txt'
title = get(handles.but_get_start,'String');
set(handles.txt_title,'String',title);
set(handles.txt_main,'String',get_start_txt);        



% --- Executes on key press with focus on but_get_start and none of its controls.
function but_get_start_KeyPressFcn(hObject, eventdata, handles)
% hObject    handle to but_get_start (see GCBO)
% eventdata  structure with the following fields (see UICONTROL)
%	Key: name of the key that was pressed, in lower case
%	Character: character interpretation of the key(s) that was pressed
%	Modifier: name(s) of the modifier key(s) (i.e., control, shift) pressed
% handles    structure with handles and user data (see GUIDATA)


% --- Executes on button press in but_model_setup.
function but_model_setup_Callback(hObject, eventdata, handles)
% hObject    handle to but_model_setup (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
load './Temps/temp_variable.mat' 'model_setup_txt'
title = get(handles.but_model_setup,'String');
set(handles.txt_title,'String',title);
set(handles.txt_main,'String',model_setup_txt);        


% --- Executes on button press in but_model_option.
function but_model_option_Callback(hObject, eventdata, handles)
% hObject    handle to but_model_option (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
load './Temps/temp_variable.mat' 'option_txt'
title = get(handles.but_model_option,'String');
set(handles.txt_title,'String',title);
set(handles.txt_main,'String',option_txt);        


% --- Executes on button press in but_forcing.
function but_forcing_Callback(hObject, eventdata, handles)
% hObject    handle to but_forcing (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
load './Temps/temp_variable.mat' 'forcing_txt'
title = get(handles.but_forcing,'String');
set(handles.txt_title,'String',title);
set(handles.txt_main,'String',forcing_txt);        


% --- Executes on button press in but_initial_cond.
function but_initial_cond_Callback(hObject, eventdata, handles)
% hObject    handle to but_initial_cond (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
load './Temps/temp_variable.mat' 'initial_txt'
title = get(handles.but_initial_cond,'String');
set(handles.txt_title,'String',title);
set(handles.txt_main,'String',initial_txt);   

% --- Executes on button press in but_viewer.
function but_viewer_Callback(hObject, eventdata, handles)
% hObject    handle to but_viewer (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
load './Temps/temp_variable.mat' 'result_txt'
title = get(handles.but_viewer,'String');
set(handles.txt_title,'String',title);
set(handles.txt_main,'String',result_txt);   
